wooahan-agile/idu-market-react

- src/scss/test.scss
implement(minjae): pull request
> implement(minjae): pull request

- src/App.js
- src/index.js
- src/pages/BoardListPage.js
- src/pages/BoardPage.js
- src/pages/HomePage.js
- src/pages/LoginPage.js
- src/pages/RegisterPage.js
- src/pages/WritePage.js
- src/scss/test.scss
> Implement(minjae): React-App 라우터 적용 #11

- src/index.js
- src/modules/auth.js
- src/modules/index.js
> Implement(minjae): React-App Set Redux #13

- src/App.scss
- src/components/Header/DropMenu.js
- src/components/Header/Header.js
- src/components/Header/HeaderMenuData.js
- src/pages/BoardListPage.js
- src/pages/HomePage.js
- src/pages/LoginPage.js
- src/scss/import/Header.scss
> 헤더 컴포넌트 구현 #15

- src/App.js
- src/components/HomePage/Section/ArticlesComponent.js
- src/components/HomePage/Section/FunctionComponent.js
- src/components/HomePage/Section/IntroduceComponent.js
- src/pages/HomePage.js
- src/scss/layout/_forms.scss
- src/scss/main.scss
- src/scss/pages/home/_articles.scss
- src/scss/pages/home/_funtion.scss
- src/scss/pages/home/_introduce.scss
- src/scss/pages/home/_mainBanner.scss
- src/scss/pages/home/_notice.scss
> Home Articles Section UI 구현

- package.json
- src/components/auth/FindIdComponent.js
- src/components/auth/FindPasswordComponent.js
- src/scss/layout/_forms.scss
> [findPassword] findPassword Page UI 및 기능 구현 

- src/components/Boards/Market/BookListComponent.js
- src/components/Boards/Market/ClothesListComponent.js
- src/components/Boards/Market/DeviceListComponent.js
> [infiniteScroll] infiniteScroll 클래스형에서 함수형으로 변환

- src/components/Profile/ProfileComponent.js
- src/redux/reducers/index.js
- src/redux/sagas/index.js
- src/redux/sagas/profileSaga.js
> [profile] Profile UI,Redux 기능 구현

- src/components/Boards/Basic/FreeBoardComponent.js
- src/components/Boards/Basic/NoticeBoardComponent.js
- src/components/Boards/BoardListItem.js
- src/components/Boards/Write/PostWriteComponent.js
> [BasicBoard]Basic Board Update

- src/redux/sagas/profileSaga.js
- src/scss/layout/boards/_basic.scss
> [basicfreeboard]  basicfreeboard UI수정

- src/components/Boards/Basic/FreeBoardComponent.js
- src/components/Boards/Basic/NoticeBoardComponent.js
- src/components/Watchlist/WatchlistBtnComponent.js
- src/components/Watchlist/WatchlistPageComponent.js
- src/pages/MainRouter.js
- src/pages/WatchlistPage/WatchlistPage.js
- src/scss/layout/boards/_basic.scss
- src/scss/layout/watchlist/_watchlist.scss
- src/scss/main.scss
> [basicBoardLoading] basicBoardLoading 기능 추가

- src/components/Boards/Comment/CommentComponent.js
- src/components/Boards/Comment/SingleComment.js
- src/scss/layout/boards/_comment.scss
> [commnet] comment 로그인 유무에 따른 생성 가능 여부 구현

- src/components/Boards/BoardListItem.js
- src/components/Boards/Search/SearchListComponent.js
- src/scss/layout/boards/_comment.scss
- src/scss/layout/boards/_market.scss
> [comment]Comment 반응형 UI 구현

- src/components/ScrollToTop.js
- src/pages/MainRouter.js
> [scrollToTop]: ScrollToTop 기능 구현

- src/components/Boards/Detail/BoardDetailTop.js
- src/scss/layout/boards/_boardWrite.scss
- src/scss/layout/boards/_market.scss
> [market] Market

- src/components/Header/DropMenu.js
- src/components/Header/Header.js
- src/components/Profile/ProfileComponent.js
- src/pages/MainRouter.js
- src/scss/layout/_header.scss
- src/scss/layout/boards/_basic.scss
> [header] Header UI Update

- src/components/Boards/BoardListItem.js
- src/components/Boards/Detail/BoardDetailComponent.js
- src/components/Boards/Detail/BoardDetailTop.js
- src/components/HomePage/Section/MainBannerComponent.js
- src/components/Profile/ProfileComponent.js
- src/components/Watchlist/WatchlistComponent.js
- src/components/purchaseAndSaleList/PurchaseListComponent.js
- src/components/purchaseAndSaleList/SaleListComponent.js
- src/pages/MainRouter.js
- src/pages/purchaseAndSaleList/PurchaseListPage.js
- src/pages/purchaseAndSaleList/SaleListPage.js
- src/redux/reducers/boardsReducer.js
- src/scss/layout/home/_mainBanner.scss
- src/scss/layout/watchlist/_watchlist.scss
> [purchaseList] Purchase list

- src/components/Boards/Market/MarketListComponent.js
- src/components/Watchlist/WatchlistComponent.js
- src/components/purchaseAndSaleList/PurchaseListComponent.js
- src/components/purchaseAndSaleList/SaleListComponent.js
- src/pages/LoadingPage.js
- src/pages/MainRouter.js
- src/redux/sagas/boardsSaga.js
- src/scss/main.scss
- src/scss/page/_loading.scss
> [codeSplitting] Code Splitting 적용

- src/components/auth/RegisterComponent.js
- src/scss/layout/_forms.scss
> [register]Register 반응형 UI

- src/components/Boards/BoardListItem.js
- src/components/Boards/Comment/ReplyComment.js
- src/components/Boards/Comment/SingleComment.js
- src/components/Boards/Detail/BoardDetailTop.js
- src/redux/reducers/boardsReducer.js
- src/redux/sagas/boardsSaga.js
- src/redux/sagas/commentSaga.js
- src/scss/layout/boards/_basic.scss
- src/scss/layout/boards/_boardDetail.scss
- src/scss/layout/boards/_comment.scss
- src/scss/layout/boards/_market.scss
> [profileImg] Profile img

- src/components/auth/RegisterComponent.js
> fix(sangjun/register): register 유효성검사 수정#115

- src/components/Boards/Basic/BasicBoardComponent.js
- src/components/Boards/BoardListItem.js
- src/components/Boards/Detail/BoardDetailTop.js
- src/components/Boards/Market/MarketListComponent.js
- src/components/Boards/Write/PostWriteComponent.js
- src/components/Editor/EditorConfig.js
- src/components/Editor/UploadAdapter.js
- src/components/Profile/ProfileComponent.js
- src/components/auth/RegisterComponent.js
- src/components/trade/TradeCompleteComponent.js
- src/hoc/auth.js
- src/pages/MainRouter.js
- src/redux/reducers/boardsReducer.js
- src/redux/reducers/profileReducer.js
- src/redux/reducers/tradeReducer.js
- src/redux/sagas/boardsSaga.js
- src/redux/sagas/tradeSaga.js
post Write 및 trade complete,  profile page fix
> [postWrite]Post Write

- src/components/Header/Header.js
- src/components/auth/FindIdComponent.js
- src/components/auth/FindPasswordComponent.js
- src/components/auth/LoginComponent.js
- src/container/HeaderMenuData.js
- src/scss/layout/_header.scss
> [login] Login , id 찾기 ,pw 찾기 UI수정

- src/components/Boards/Comment/ReplyComment.js
- src/components/Boards/Comment/SingleComment.js
- src/components/Profile/ProfileComponent.js
- src/scss/layout/profile/_profile.scss
- src/scss/page/_404.scss
- src/scss/page/_loading.scss
> [profile]Profile

- package.json
- src/pages/Boards/Basic/FreeBoardPage.js
- src/pages/Boards/Basic/NoticeBoardPage.js
- src/pages/Boards/Detail/BoardDetailPage.js
- src/pages/Boards/Market/BookListPage.js
- src/pages/Boards/Market/ClothesListPage.js
- src/pages/Boards/Market/DeviceListPage.js
- src/pages/Boards/Search/MarketSearchPage.js
- src/pages/Boards/Update/PostUpdatePage.js
- src/pages/Boards/Write/PostWritePage.js
- src/pages/HomePage/HomePage.js
- src/pages/MainRouter.js
- src/pages/Page404.js
- src/pages/Profile/ProfilePage.js
- src/pages/Profile/ProfileUpdatePage.js
- src/pages/Trade/TradeCompletePage.js
- src/pages/WatchlistPage/WatchlistPage.js
- src/pages/authPages/FindIdPage.js
- src/pages/authPages/FindPasswordPage.js
- src/pages/authPages/LoginPage.js
- src/pages/authPages/RegisterPage.js
- src/pages/purchaseAndSaleList/PurchaseListPage.js
- src/pages/purchaseAndSaleList/SaleListPage.js
- yarn.lock
> [reactHelmet]React helmet

- src/components/Boards/Update/PostUpdateComponent.js
- src/components/Boards/Write/PostWriteComponent.js
- src/redux/sagas/boardsSaga.js
> [modal] Modal 제거

- src/components/Boards/Update/PostUpdateComponent.js
- src/components/Boards/Write/PostWriteComponent.js
- src/components/Footer/Footer.js
- src/components/HomePage/Section/IntroduceComponent.js
- src/redux/sagas/boardsSaga.js
> [delete] 불필요한 console 제거

- package-lock.json
- src/components/Boards/Basic/BasicBoardComponent.js
- src/scss/layout/boards/_basic.scss
> [basicBoard] basicBoard 깨짐현상 수정 #135

- src/components/Boards/Write/PostWriteComponent.js
- src/scss/layout/home/_notice.scss
> [notice]Notice
